### ISSUE TITLE
[Bug] 更新腳本文件出錯

### ISSUE THREAD

**Issue by xeivu** [Night-stars-1/Auto_Star_Rail#27]
### 问题描述

地圖和圖片更新沒有問題,唯獨腳本更新出錯

或請求手動更新文件

### 预期行为

更新成功

### 实际行为

C:\Windows\System32>"C:\Auto_Star_Rail-main\Honkai_Star_Rail.py"
星穹铁道小助手为开源项目，完全免费
如果你是购买的那么你被骗了
开源仓库地址: https://github.com/Night-stars-1/Auto_Star_Rail
? 请选择运行项目 更新资源(脚本)
? 请选择更新项目 脚本
update_file.update_file_main:406 - 0/20230830203446/20230830203446 - [资源文件更新]即将资源文件更新，本操作会覆盖本地脚本文件..
update_file.upsra:145 - 0/20230830203446/20230830203446 - [资源文件更新]本地版本与远程版本不符，开始更新资源文件->https://ghproxy.com/https://github.com/Night-stars-1/Auto_Star_Rail/archive/refs/tags/v1.7.3.zip
v1.7.3.zip: 23.6MiB [00:05, 4.84MiB/s]
update_file.upsra:149 - 0/20230830203446/20230830203446 - [资源文件更新]下载更新包成功, 正在覆盖本地文件: 0 -> v1.7.3
解压中: 100%|█████████████████████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 455.97it/s]
Honkai_Star_Rail.<module>:355 - 0/20230830203446/20230830203446 - Traceback (most recent call last):
  File "C:\Auto_Star_Rail-main\Honkai_Star_Rail.py", line 348, in <module>
    select() if not serial_map else sra.main(start=serial_map)
    ^^^^^^^^
  File "C:\Auto_Star_Rail-main\Honkai_Star_Rail.py", line 341, in select
    sra.up_data()
  File "C:\Auto_Star_Rail-main\Honkai_Star_Rail.py", line 272, in up_data
    update_file().update_file_main(**self.updata_dict[option])
  File "C:\Auto_Star_Rail-main\utils\update_file.py", line 407, in update_file_main
    check_file_status = asyncio.run(self.update_file(False,skip_verify,type,version,url_zip,unzip_path,keep_folder,keep_file,zip_path,name,delete_file))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Auto_Star_Rail-main\utils\update_file.py", line 274, in update_file
    return await self.upsra(rm_all, skip_verify, type, version, url_zip, unzip_path, keep_folder, keep_file, zip_path, name, delete_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Auto_Star_Rail-main\utils\update_file.py", line 164, in upsra
    await self.remove_file(unzip_path, keep_folder, keep_file)
  File "C:\Auto_Star_Rail-main\utils\update_file.py", line 85, in remove_file
    os.remove(item_path)
PermissionError: [WinError 5] 存取被拒。: '.\\0ae3b998-9a38-4b72-a4c4-06849441518d_Servicing-Stack.dll'

### 截图或录屏

![螢幕擷取畫面 2023-09-09 175750](https://github.com/Night-stars-1/Auto_Star_Rail/assets/133697094/6057e33f-6309-4d88-a1ff-5f272c849204)

### 自动锄大地脚本版本

1.7.3

### 星穹铁道区服

国际服

### 运行的客户端

PC

### 日志

無

**Comment by xeivu** [comment]
用1.7.1版本腳本更新成功
